receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  attributes:
    actions:
      - key: environment
        value: ${OTEL_ENVIRONMENT}
        action: insert
      - key: service.namespace
        value: ${OTEL_SERVICE_NAMESPACE}
        action: insert
  resourcedetection:
    detectors: [env, system, docker]
    timeout: 2s
    override: false
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      - name: error-in-trace
        type: status_code
        status_code: ERROR

exporters:
  jaeger:
    endpoint: ${JAEGER_COLLECTOR_ENDPOINT}
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:${PROMETHEUS_PORT}"
    namespace: ${PROMETHEUS_NAMESPACE}
    const_labels:
      environment: ${OTEL_ENVIRONMENT}
  logging:
    loglevel: debug

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [prometheus]